# Generated by Django 3.2.6 on 2021-08-12 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=30)),
                ('cfees', models.IntegerField()),
                ('cduration', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'course',
            },
        ),
    ]
